name: Onboard AI Landing Zone

on:
  workflow_dispatch:
    inputs:
      subscription_id:
        description: "Azure Subscription ID where AI Landing Zone will be onboarded"
        required: true
        type: string
      appid:
        description: "Application ID. Identifier of the application"
        required: true
        type: string
        default: "12345"

permissions:
  id-token: write
  contents: read

env:
    AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    TF_VAR_ONBOARD_SUB_ID: ${{ github.event.inputs.subscription_id }}
    TF_VAR_APPID: ${{ github.event.inputs.appid }}
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_USE_OIDC: true


jobs:
    onboard-job:
        name: Onboard AI Landing Zone
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Terraform
            uses: hashicorp/setup-terraform@v3

          - name: Azure Login
            uses: azure/login@v2
            with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          - name: Terraform Init
            working-directory: onboarding
            run: terraform init

          - name: Terraform Validate
            working-directory: onboarding
            run: terraform validate

          - name: Terraform Apply
            working-directory: onboarding
            run: terraform apply -auto-approve
